<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class DatabaseSeeder extends Seeder
{
    public function run()
    {
        DB::table('users')->insert([
            [
                'email' => 'admin@example.com',
                'password' => Hash::make('123'),
                'username' => 'admin',
                'role' => 'Admin',
                'created_at' => now(),
                'created_by' => 'system',
                'updated_at' => now(),
                'updated_by' => 'system',
            ],
            [
                'email' => 'kasir@example.com',
                'password' => Hash::make('123'),
                'username' => 'kasir',
                'role' => 'Kasir',
                'created_at' => now(),
                'created_by' => 'system',
                'updated_at' => now(),
                'updated_by' => 'system',
            ]
        ]);

        DB::table('pelanggan')->insert([
            [
                'nama_pelanggan' => 'Budi Santoso',
                'tipe' => 'Reguler',
                'alamat' => 'Jl. Merdeka No. 1',
                'notelp' => '08123456789',
                'poin' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 'admin',
                'updated_by' => 'admin',
            ],
            [
                'nama_pelanggan' => 'Dimas Santoso',
                'tipe' => 'VIP',
                'alamat' => 'Jl. Merdeka No. 1',
                'notelp' => '08123456789',
                'poin' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 'admin',
                'updated_by' => 'admin',
            ],
            [
                'nama_pelanggan' => 'Boby Santoso',
                'tipe' => 'VVIP',
                'alamat' => 'Jl. Merdeka No. 1',
                'notelp' => '08123456789',
                'poin' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 'admin',
                'updated_by' => 'admin',
            ],
        ]);

        DB::table('kategori')->insert([
            [
                'kode_kategori' => 'XD001',
                'nama_kategori' => 'Elektronik',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori' => 'XD002',
                'nama_kategori' => 'Aksesoris',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('produk')->insert([
            [
                'kode_produk' => 'PRD001',
                'nama_produk' => 'Laptop ASUS',
                'kategoriid' => 1,
                'harga_beli' => 7000000,
                'harga_jual' => 8400000,
                'stock' => 9,
                'minimal_stock' => 2,
                'tanggal_pembelian' => now(),
                'tanggal_kadaluarsa' => now()->addYears(3), // Contoh masa kadaluarsa 3 tahun
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 'admin',
                'updated_by' => 'admin',
            ],
            [
                'kode_produk' => 'PRD002',
                'nama_produk' => 'Laptop Lenovo',
                'kategoriid' => 1,
                'harga_beli' => 8000000,
                'harga_jual' => 9600000,
                'stock' => 10,
                'minimal_stock' => 2,
                'tanggal_pembelian' => now(),
                'tanggal_kadaluarsa' => now()->addYears(3), // Contoh masa kadaluarsa 3 tahun
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 'admin',
                'updated_by' => 'admin',
            ],
            [
                'kode_produk' => 'PRD003',
                'nama_produk' => 'Laptop HP',
                'kategoriid' => 1,
                'harga_beli' => 6000000,
                'harga_jual' => 6120000,
                'stock' => 10,
                'minimal_stock' => 2,
                'tanggal_pembelian' => now(),
                'tanggal_kadaluarsa' => now()->addYears(-3),
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 'admin',
                'updated_by' => 'admin',
            ],
            [
                'kode_produk' => 'DRX001',
                'nama_produk' => 'Mouse Wired',
                'kategoriid' => 2,
                'harga_beli' => 26000,
                'harga_jual' => 31200,
                'stock' => 18,
                'minimal_stock' => 2,
                'tanggal_pembelian' => now(),
                'tanggal_kadaluarsa' => now()->addYears(3),
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 'admin',
                'updated_by' => 'admin',
            ],
            [
                'kode_produk' => 'DRX002',
                'nama_produk' => 'Mouse Wireless',
                'kategoriid' => 2,
                'harga_beli' => 86000,
                'harga_jual' => 103200,
                'stock' => 12,
                'minimal_stock' => 2,
                'tanggal_pembelian' => now(),
                'tanggal_kadaluarsa' => now()->addYears(3),
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 'admin',
                'updated_by' => 'admin',
            ],
            [
                'kode_produk' => 'ERX001',
                'nama_produk' => 'Keyboard Wired',
                'kategoriid' => 2,
                'harga_beli' => 52000,
                'harga_jual' => 62400,
                'stock' => 16,
                'minimal_stock' => 2,
                'tanggal_pembelian' => now(),
                'tanggal_kadaluarsa' => now()->addYears(3),
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 'admin',
                'updated_by' => 'admin',
            ],
            [
                'kode_produk' => 'ERX002',
                'nama_produk' => 'Keyboard Wireless',
                'kategoriid' => 2,
                'harga_beli' => 150000,
                'harga_jual' => 180000,
                'stock' => 12,
                'minimal_stock' => 2,
                'tanggal_pembelian' => now(),
                'tanggal_kadaluarsa' => now()->addYears(3),
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 'admin',
                'updated_by' => 'admin',
            ],
        ]);


        DB::table('diskon')->insert([
            [
                'produkid' => 1,
                'diskon' => 10,
                'berlaku_sampai' => Carbon::now()->addDays(-30),
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 'admin',
                'updated_by' => 'admin',
            ],
            [
                'produkid' => 2,
                'diskon' => 10,
                'berlaku_sampai' => Carbon::now()->addDays(30),
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 'admin',
                'updated_by' => 'admin',
            ],
        ]);

        DB::table('laporan')->insert([
            [
                'userid' => 1,
                'pelangganid' => 1,
                'tanggal_waktu' => Carbon::now()->startOfWeek(Carbon::SUNDAY),
                'tipe' => 'Reguler',
                'subtotal' => 7500000,
                'diskonRp' => 750000,
                'poin_use' => 50,
                'hargatotal' => 6750000,
                'created_at' => Carbon::now()->startOfWeek(Carbon::SUNDAY),
                'updated_at' => now(),
                'created_by' => 'admin',
                'updated_by' => 'admin',
            ],
            [
                'userid' => 1,
                'pelangganid' => 1,
                'tanggal_waktu' => Carbon::now()->startOfWeek(Carbon::SUNDAY)->addDay(),
                'tipe' => 'Reguler',
                'subtotal' => 7600000,
                'diskonRp' => 760000,
                'poin_use' => 55,
                'hargatotal' => 6840000,
                'created_at' => Carbon::now()->startOfWeek(Carbon::SUNDAY)->addDay(),
                'updated_at' => now(),
                'created_by' => 'admin',
                'updated_by' => 'admin',
            ],
            [
                'userid' => 1,
                'pelangganid' => 1,
                'tanggal_waktu' => Carbon::now()->startOfWeek(Carbon::SUNDAY)->addDay(),
                'tipe' => 'Reguler',
                'subtotal' => 7600000,
                'diskonRp' => 760000,
                'poin_use' => 55,
                'hargatotal' => 6840000,
                'created_at' => Carbon::now()->startOfWeek(Carbon::SUNDAY)->addDay(),
                'updated_at' => now(),
                'created_by' => 'admin',
                'updated_by' => 'admin',
            ],
            [
                'userid' => 1,
                'pelangganid' => 1,
                'tanggal_waktu' => Carbon::now()->startOfWeek(Carbon::SUNDAY)->addDay(),
                'tipe' => 'Reguler',
                'subtotal' => 7600000,
                'diskonRp' => 760000,
                'poin_use' => 55,
                'hargatotal' => 6840000,
                'created_at' => Carbon::now()->startOfWeek(Carbon::SUNDAY)->addDay(),
                'updated_at' => now(),
                'created_by' => 'admin',
                'updated_by' => 'admin',
            ],
            [
                'userid' => 1,
                'pelangganid' => 1,
                'tanggal_waktu' => Carbon::now()->startOfWeek(Carbon::SUNDAY)->addDays(2),
                'tipe' => 'Reguler',
                'subtotal' => 7700000,
                'diskonRp' => 770000,
                'poin_use' => 60,
                'hargatotal' => 6930000,
                'created_at' => Carbon::now()->startOfWeek(Carbon::SUNDAY)->addDays(2),
                'updated_at' => now(),
                'created_by' => 'admin',
                'updated_by' => 'admin',
            ],
            [
                'userid' => 1,
                'pelangganid' => 1,
                'tanggal_waktu' => Carbon::now()->startOfWeek(Carbon::SUNDAY)->addDays(3),
                'tipe' => 'Reguler',
                'subtotal' => 7800000,
                'diskonRp' => 780000,
                'poin_use' => 65,
                'hargatotal' => 7020000,
                'created_at' => Carbon::now()->startOfWeek(Carbon::SUNDAY)->addDays(3),
                'updated_at' => now(),
                'created_by' => 'admin',
                'updated_by' => 'admin',
            ],
            [
                'userid' => 1,
                'pelangganid' => 1,
                'tanggal_waktu' => Carbon::now()->startOfWeek(Carbon::SUNDAY)->addDays(3),
                'tipe' => 'Reguler',
                'subtotal' => 7800000,
                'diskonRp' => 780000,
                'poin_use' => 65,
                'hargatotal' => 7020000,
                'created_at' => Carbon::now()->startOfWeek(Carbon::SUNDAY)->addDays(3),
                'updated_at' => now(),
                'created_by' => 'admin',
                'updated_by' => 'admin',
            ],
            [
                'userid' => 1,
                'pelangganid' => 1,
                'tanggal_waktu' => Carbon::now()->startOfWeek(Carbon::SUNDAY)->addDays(4),
                'tipe' => 'Reguler',
                'subtotal' => 7900000,
                'diskonRp' => 790000,
                'poin_use' => 70,
                'hargatotal' => 7110000,
                'created_at' => Carbon::now()->startOfWeek(Carbon::SUNDAY)->addDays(4),
                'updated_at' => now(),
                'created_by' => 'admin',
                'updated_by' => 'admin',
            ],
            [
                'userid' => 1,
                'pelangganid' => 1,
                'tanggal_waktu' => Carbon::now()->startOfWeek(Carbon::SUNDAY)->addDays(4),
                'tipe' => 'Reguler',
                'subtotal' => 7900000,
                'diskonRp' => 790000,
                'poin_use' => 70,
                'hargatotal' => 7110000,
                'created_at' => Carbon::now()->startOfWeek(Carbon::SUNDAY)->addDays(4),
                'updated_at' => now(),
                'created_by' => 'admin',
                'updated_by' => 'admin',
            ],
            [
                'userid' => 1,
                'pelangganid' => 1,
                'tanggal_waktu' => Carbon::now()->startOfWeek(Carbon::SUNDAY)->addDays(5),
                'tipe' => 'Reguler',
                'subtotal' => 8000000,
                'diskonRp' => 800000,
                'poin_use' => 75,
                'hargatotal' => 7200000,
                'created_at' => Carbon::now()->startOfWeek(Carbon::SUNDAY)->addDays(5),
                'updated_at' => now(),
                'created_by' => 'admin',
                'updated_by' => 'admin',
            ],
            [
                'userid' => 1,
                'pelangganid' => 1,
                'tanggal_waktu' => Carbon::now()->startOfWeek(Carbon::SUNDAY)->addDays(5),
                'tipe' => 'Reguler',
                'subtotal' => 8000000,
                'diskonRp' => 800000,
                'poin_use' => 75,
                'hargatotal' => 7200000,
                'created_at' => Carbon::now()->startOfWeek(Carbon::SUNDAY)->addDays(5),
                'updated_at' => now(),
                'created_by' => 'admin',
                'updated_by' => 'admin',
            ],
            [
                'userid' => 1,
                'pelangganid' => 1,
                'tanggal_waktu' => Carbon::now()->startOfWeek(Carbon::SUNDAY)->addDays(5),
                'tipe' => 'Reguler',
                'subtotal' => 8000000,
                'diskonRp' => 800000,
                'poin_use' => 75,
                'hargatotal' => 7200000,
                'created_at' => Carbon::now()->startOfWeek(Carbon::SUNDAY)->addDays(5),
                'updated_at' => now(),
                'created_by' => 'admin',
                'updated_by' => 'admin',
            ],
            [
                'userid' => 1,
                'pelangganid' => 1,
                'tanggal_waktu' => Carbon::now()->startOfWeek(Carbon::SUNDAY)->addDays(6),
                'tipe' => 'Reguler',
                'subtotal' => 8100000,
                'diskonRp' => 810000,
                'poin_use' => 80,
                'hargatotal' => 7290000,
                'created_at' => Carbon::now()->startOfWeek(Carbon::SUNDAY)->addDays(6),
                'updated_at' => now(),
                'created_by' => 'admin',
                'updated_by' => 'admin',
            ],
        ]);
        
    }
}
